# This is a basic workflow to help you get started with Actions

name: Windows checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  windows-build-test:
    timeout-minutes: 40
    runs-on: [self-hosted, windows, x64]
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Clear workspace
        run: |
          Remove-Item -Path "${{ github.workspace }}\*" -Recurse -Force

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive          
        
      - name: Update thirdparty
        run: thirdparty\install.bat

      - name: Integrate vcpkg
        run: vcpkg integrate install
        
      - name: Build
        run: py -3 scripts\build_script.py ${{ matrix.config }}
        
      - name: Unit Tests
        run: py -3 scripts\run_unit_test_script.py ${{ matrix.config }}

      - name: Python Tests
        working-directory: source\x64\${{ matrix.config }}
        run: py -3 ..\..\..\scripts\run_python_test_script.py

      - name: Clear workspace
        run: |
          Remove-Item -Path "${{ github.workspace }}\*" -Recurse -Force
